// Segment metadata for Interactive Video
// Auto-generated by SCORM export
// Video ID: 643e6fca7b6e431c87b0af2cc40bc1d0

window.SEGMENT_METADATA = [
  {
    "segmentId": "default",
    "videoId": "643e6fca7b6e431c87b0af2cc40bc1d0",
    "sceneIds": [
      "w6iWfDzY",
      "35D3G6k4",
      "vlTrytu3",
      "5hWcOH6L",
      "lr7OMkFv",
      "OPGWDjV7",
      "MMubtwXZ",
      "4WWhXoc1",
      "ihSJ3Hvf",
      "0LqGtMzt",
      "bnQUV7SY",
      "j77Ffs5n",
      "vRvwGOTt",
      "MqerXjxE",
      "td3hvci3",
      "5LMW4OIx"
    ],
    "videoUrl": "https://resource2.heygen.ai/aws_pacific/avatar_tmp/6d88f4bf84fa43d5879291f8cc0b673b/vReZcjoX4OV7O0hdopjATfJCZG98kTHk7/caption_643e6fca7b6e431c87b0af2cc40bc1d0.mp4"
  }
];
