// Segment metadata for Interactive Video
// Auto-generated by SCORM export
// Video ID: 24462cbe7ddf41e7986d91ab20982f36

window.SEGMENT_METADATA = [
  {
    "segmentId": "default",
    "videoId": "24462cbe7ddf41e7986d91ab20982f36",
    "sceneIds": [
      "0OH38hBv",
      "Bq4T6JTe",
      "TfDX7MYL",
      "pwHMNHXy",
      "Z7B5SS5N",
      "mvWlAQIG",
      "RTqpM0DB",
      "rnDPgowK",
      "ZKivxTQI",
      "959jMmYv",
      "Ce9amI70",
      "CmZ95iJy",
      "B4HjZqI6",
      "zM7aBv9I",
      "bXQvWQMa",
      "xjQHZYma"
    ],
    "videoUrl": "https://resource2.heygen.ai/aws_pacific/avatar_tmp/6d88f4bf84fa43d5879291f8cc0b673b/v0D1zB7BCK94MF2StMYKtD1ucftcI21c8/caption_24462cbe7ddf41e7986d91ab20982f36.mp4"
  }
];
