// Segment metadata for Interactive Video
// Auto-generated by SCORM export
// Video ID: e84b0f2965f24b4f8f356f1294f7efcc

window.SEGMENT_METADATA = [
  {
    "segmentId": "default",
    "videoId": "e84b0f2965f24b4f8f356f1294f7efcc",
    "sceneIds": [
      "iRltULdf",
      "J7ZmSczg",
      "JkJg5qFh",
      "BtbggdZh",
      "EObqQCDz",
      "LuOfNNWH",
      "zYCEzA0l",
      "KIGVMNdu",
      "gPLcKtm8",
      "TTw1F8xf",
      "hmaI5JXE",
      "uhk6Qgjy",
      "VChRZekR",
      "EhzNYPPR",
      "j5Tdx7Q5",
      "yn8QWpAi",
      "Ynw1LB5Y",
      "1jVMPmQU",
      "xy54MRbm"
    ],
    "videoUrl": "https://resource2.heygen.ai/aws_pacific/avatar_tmp/6d88f4bf84fa43d5879291f8cc0b673b/v15FTfHsvzTML1mfy1dreApxYkko6D5Br/caption_e84b0f2965f24b4f8f356f1294f7efcc.mp4"
  }
];
